// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PTM.DAL.Entities;

public partial class PtmRole
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool Isactive { get; set; }
}