// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PTM.DAL.Entities;

public partial class PtmTicket
{
    public int Ticketid { get; set; }

    public int Vehicleid { get; set; }

    public int Parkinglotid { get; set; }

    public int Userid { get; set; }

    public DateTime? Issuedate { get; set; }

    public DateTime Intime { get; set; }

    public DateTime? Outtime { get; set; }

    public DateTime? Expirationdate { get; set; }

    public decimal? Fineamount { get; set; }

    public bool? Ispaid { get; set; }

    public string Remarks { get; set; }

    public decimal? Discount { get; set; }

    public int? Ticketnumber { get; set; }

    public virtual PtmParkinglot Parkinglot { get; set; }

    public virtual PtmUser User { get; set; }

    public virtual PtmVehicle Vehicle { get; set; }
}