// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PTM.DAL.Entities;

public partial class PtmUserotp
{
    public int Id { get; set; }

    public int? Userid { get; set; }

    public string Otpcode { get; set; }

    public DateTime Expirationtime { get; set; }

    public bool Isused { get; set; }

    public virtual PtmUser User { get; set; }
}