// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PTM.DAL.Entities;

public partial class PtmVehicle
{
    public int Vehicleid { get; set; }

    public string Licenseplate { get; set; }

    public string Ownername { get; set; }

    public DateTime? Createddate { get; set; }

    public int? Categoryid { get; set; }

    public virtual PtmCategory Category { get; set; }

    public virtual ICollection<PtmTicket> PtmTickets { get; set; } = new List<PtmTicket>();
}